version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd

  mongo-seeding:
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=password
    depends_on:
      - mongo

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./api/:/app
    environment:
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=password
      - NODE_ENV=development
    depends_on:
      - mongo
      - mongo-seeding
